create sign up, login and register
PhucNguyenKhac/base-android-source-mock pull request #1
Opened 2023-07-11 07:44 UTC by hoanghai126

Anh review cho em voi a

2023-07-12 08:55 UTC, NguyenKhacPhuc commented on app/src/main/res/layout/fragment_sign_up.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
try to use constrait layout with complex UI

2023-07-12 08:55 UTC, NguyenKhacPhuc commented on app/src/main/res/layout/layout_register.xml
> +    <include
use toolbar of Android, and CollapseToolBar if possible

2023-07-12 09:05 UTC, tranconguet commented
Please format code before create Merge request

2023-07-12 09:06 UTC, tranconguet commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Should remove unused string

2023-07-12 09:12 UTC, tranconguet commented on app/src/main/res/layout/fragment_sign_up.xml
Please use the same convention when set id name for view. Eg. tvSignUp, rlContinuePhoneNumber, ivGoogle, etc.

2023-07-12 09:15 UTC, tranconguet commented on app/src/main/res/layout/layout_register.xml
> +            android:text="Have An Account?"
Should define string resource

2023-07-12 09:16 UTC, tranconguet commented on app/src/main/res/layout/layout_toolbar.xml
Please use camelCase or underscore only

2023-07-12 09:23 UTC, tranconguet requested changes, later dismissed
Please resolve all comments

2023-07-13 03:00 UTC, NguyenKhacPhuc commented on app/src/main/res/layout/fragment_sign_up.xml
> +        <RelativeLayout
use drawableLeft, no need to create new layout for this

2023-07-13 03:01 UTC, thaoqs280899 commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:layout_marginStart="30dp"
The values of dp should be moved to dimen file

2023-07-13 03:01 UTC, thaoqs280899 commented on app/src/main/res/layout/layout_login.xml
> +            android:layout_marginTop="15dp"
The values of margin should divisible by 4

2023-07-13 03:01 UTC, thaoqs280899 commented on app/src/main/res/layout/fragment_sign_up.xml
> +        android:background="#000000"
Using @color/colorPrimaryDark

2023-07-13 03:08 UTC, NguyenKhacPhuc commented on app/src/main/res/drawable/blur_overlay.xml
> +        android:centerColor="#00ffffff"
move color to color file for future use

2023-07-13 03:09 UTC, NguyenKhacPhuc commented on app/src/main/res/drawable/custom_image_icon_left.xml
> +        android:width="0.01dp"/>
why use this dp? does it too small?

2023-07-13 03:10 UTC, NguyenKhacPhuc commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:layout_marginEnd="8dp"
should move to dimens file for future use

2023-07-15 13:40 UTC, NguyenKhacPhuc approved these changes

2023-07-15 13:44 UTC, merged